### PR TITLE
Some cleanup and better logging for memory-related issues

### PR DESCRIPTION
**Pull request by oxtoacart**
Addresses getlantern/lantern-internal#433

### CODE REVIEW

**Comment by joesis** [comment]
I encountered a deadlock but never reproduced. Fortunately, there's a panic log. I also added test to check if the stats correctly calculated, in a new PR, but `numVirtualConnections` is not decreased.

```
goroutine 5 [runnable]:
github.com/getlantern/cmux.(*listener).Close(0xc42006e900, 0x0, 0x0)
	/Users/joesis/workspace/go/src/github.com/getlantern/cmux/listener.go:136 +0x29f
github.com/getlantern/cmux.TestRoundTrip.func2(0xc42006e900, 0xc42000de40, 0xc42008c180, 0xc4200153e0)
	/Users/joesis/workspace/go/src/github.com/getlantern/cmux/cmux_test.go:47 +0x32
github.com/getlantern/cmux.TestRoundTrip(0xc42008c180)
	/Users/joesis/workspace/go/src/github.com/getlantern/cmux/cmux_test.go:119 +0x1ad8
testing.tRunner(0xc42008c180, 0x2e8ad0)
	/usr/local/Cellar/go/1.7.3/libexec/src/testing/testing.go:610 +0x81
created by testing.(*T).Run
	/usr/local/Cellar/go/1.7.3/libexec/src/testing/testing.go:646 +0x2ec

goroutine 9 [semacquire]:
sync.runtime_Semacquire(0xc42006e954)
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/sema.go:47 +0x30
sync.(*Mutex).Lock(0xc42006e950)
	/usr/local/Cellar/go/1.7.3/libexec/src/sync/mutex.go:85 +0xd0
github.com/getlantern/cmux.(*listener).Close(0xc42006e900, 0x0, 0x0)
	/Users/joesis/workspace/go/src/github.com/getlantern/cmux/listener.go:122 +0x66
github.com/getlantern/cmux.(*listener).listen(0xc42006e900)
	/Users/joesis/workspace/go/src/github.com/getlantern/cmux/listener.go:59 +0x13b
created by github.com/getlantern/cmux.Listen
	/Users/joesis/workspace/go/src/github.com/getlantern/cmux/listener.go:47 +0x187

goroutine 10 [semacquire]:
sync.runtime_Semacquire(0xc42006e954)
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/sema.go:47 +0x30
sync.(*Mutex).Lock(0xc42006e950)
	/usr/local/Cellar/go/1.7.3/libexec/src/sync/mutex.go:85 +0xd0
github.com/getlantern/cmux.(*listener).logStats(0xc42006e900)
	/Users/joesis/workspace/go/src/github.com/getlantern/cmux/listener.go:159 +0x172
created by github.com/getlantern/cmux.Listen
	/Users/joesis/workspace/go/src/github.com/getlantern/cmux/listener.go:48 +0x1a9
```

**Comment by joesis** [comment]
I ended up adding commit directly, as it only involves test file. @oxtoacart Feel free to revert 335de6f7 or modify it if it's incorrect.

**Comment by joesis** [comment]
Fixed the test in 7c61e95 but encountered deadlock again. Attached the full log.

[deadlock.txt](https://github.com/getlantern/cmux/files/618608/deadlock.txt)

**Comment by oxtoacart** [comment]
@joesis Thanks for the test and noticing the deadlock. It looks like it's actually in the smux package, so I'm forking and fixing now.

**Comment by oxtoacart** [comment]
Here's a Pull Request to smux that fixes the deadlock - https://github.com/xtaci/smux/pull/8

I'm temporarily pointing at our fork of smux which has this fix. Once the smux PR is merged, I'll switch back to the xtaci repo.

This handy snippet made detecting the deadlock relatively reliable:

```bash
for i in {1..50}; do go test -race -timeout 10s; done
```

**Comment by joesis** [comment]
Ha, I only tried `{0..10}`, should be more aggressive.

LGTM now!

**Pull request merged**
